// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqWmfEnbn1DzYQ29XixXNaHUrnaVZ5Tzk',
    appId: '1:348197494548:web:5c17beee76f09d552cac01',
    messagingSenderId: '348197494548',
    projectId: 'luar-sekolah-lms-95912',
    authDomain: 'luar-sekolah-lms-95912.firebaseapp.com',
    storageBucket: 'luar-sekolah-lms-95912.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ehik0Q5O5cxFSYxeRLK37eB8a5z_47k',
    appId: '1:348197494548:android:bd9ca1d54a19194d2cac01',
    messagingSenderId: '348197494548',
    projectId: 'luar-sekolah-lms-95912',
    storageBucket: 'luar-sekolah-lms-95912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lzo7_cxsBrIN9cqcmNl86iDuGugXr_A',
    appId: '1:348197494548:ios:d533fb2cb93b4aa02cac01',
    messagingSenderId: '348197494548',
    projectId: 'luar-sekolah-lms-95912',
    storageBucket: 'luar-sekolah-lms-95912.firebasestorage.app',
    iosBundleId: 'com.example.luarSekolahLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2lzo7_cxsBrIN9cqcmNl86iDuGugXr_A',
    appId: '1:348197494548:ios:d533fb2cb93b4aa02cac01',
    messagingSenderId: '348197494548',
    projectId: 'luar-sekolah-lms-95912',
    storageBucket: 'luar-sekolah-lms-95912.firebasestorage.app',
    iosBundleId: 'com.example.luarSekolahLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqWmfEnbn1DzYQ29XixXNaHUrnaVZ5Tzk',
    appId: '1:348197494548:web:106f9ea4307ea65c2cac01',
    messagingSenderId: '348197494548',
    projectId: 'luar-sekolah-lms-95912',
    authDomain: 'luar-sekolah-lms-95912.firebaseapp.com',
    storageBucket: 'luar-sekolah-lms-95912.firebasestorage.app',
  );

}